- name: Configure instance(s)
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    migrate_db: 'yes'
    openid_workaround: true
    EDXAPP_LMS_NGINX_PORT: '80'
    EDX_ANSIBLE_DUMP_VARS: true
    # used for releases
    edx_platform_version: '{{ OPENEDX_RELEASE | default("release") }}'
    ora2_version: '{{ OPENEDX_RELEASE | default("master") }}'
    certs_version: '{{ OPENEDX_RELEASE | default("master") }}'
    forum_version: '{{ OPENEDX_RELEASE | default("master") }}'
    xqueue_version: '{{ OPENEDX_RELEASE | default("master") }}'
  vars_files:
    - "group_vars/all"
  roles:
    - user
    - role: nginx
      nginx_sites:
      - cms
      - lms
      - forum
      - xqueue
      - certs
      - xserver
      nginx_default_sites:
      - lms
    - edxlocal
    - mongo
    - { role: 'edxapp', celery_worker: True }
    - edxapp
    - demo
    - { role: 'rabbitmq', rabbitmq_ip: '127.0.0.1' }
    - oraclejdk
    - elasticsearch
    - forum
    - { role: "xqueue", update_users: True }
    - certs
    - xserver
    - role: analytics-api
      when: ANALYTICS_API_GIT_IDENTITY
    - edx_ansible
